### ISSUE TITLE
Add comment commands

### ISSUE THREAD

**Issue by the1076** [ibanner56/OtherDave#1]
Implement issuing commands to OtherDave by way of making comments to it, via Discord.
An example would be to have OtherDave change the DrunkDraw time by commenting what the new time for the drunk draw is.

**Comment by ibanner56** [comment]
I'll have to see if Discord bots can respond to mentions - I would assume so. All I know how to do so far is bang ('!') commands.

**Comment by ibanner56** [comment]
I was thinking something more like '!drunkdraw --date 12', for example.

**Comment by ibanner56** [comment]
!drunkdraw takes message flags to update it now.
