### ISSUE TITLE
LWYS character selection needs to be clearer

### ISSUE THREAD

**Issue by MercWorks** [ibanner56/OtherDave#191]
![image](https://user-images.githubusercontent.com/1631598/200656608-f51cee56-9ef4-495d-a02f-937da82d6acd.png)
![image](https://user-images.githubusercontent.com/1631598/200656618-5213e9a9-5acf-4c93-a526-9d797e017f0c.png)

**Comment by ibanner56** [comment]
Right now it's a mess and hard to get right
