### ISSUE TITLE
!comic command

### ISSUE THREAD

**Issue by MercWorks** [ibanner56/OtherDave#2]
When a user uses the !comic command, generate a random phrase based on three separate lists representing the first, second, and third panels. Maybe eventually random images??

**Comment by ibanner56** [comment]
Sort of like Explosim's random generator?

**Comment by MercWorks** [comment]
Exactly like that

**Comment by ibanner56** [comment]
Did you want this to be phrases or images?

**Comment by MercWorks** [comment]
MMM images

**Comment by ibanner56** [comment]
MMM then I need some help on your end with regards to resources - OtherDave isn't going to be drawing panels himself.

**Comment by ibanner56** [comment]
Implemented in v0.1.0.
