### ISSUE TITLE
Randomly selected folder branches for comic generator

### ISSUE THREAD

**Issue by MercWorks** [ibanner56/OtherDave#7]
Have comic generator choose an available branch at random when !comic is used.
IE:
a_comic/panel01
b_comic/panel01
c_comic/panel01, etc

Optional thought: add a command that'll allow a user to request a specific branch?
IE:
!comic a_comic
!comic b_comic etc

**Comment by ibanner56** [comment]
We'll have to pick a date/time to switch over from one to the other, since it's a breaking change if we only swap one side or the other.

I'll start the work on my end and let you know when OtherDave is set to switch.
