### ISSUE TITLE
!mimic mloc shows same sentence every time

### ISSUE THREAD

**Issue by MercWorks** [ibanner56/OtherDave#98]
!mimic @mloc shows:
1000000 seems v large. is that just a noob but I have difficulty keeping small leaves in.
1000000 seems v large. is that just a noob but I have difficulty keeping small leaves in.
1000000 seems v large. is that just a noob but I have difficulty keeping small leaves in.

It's really important to mloc that we get mimic working, he's very sick and it's his soul's deepest desire

**Comment by ibanner56** [comment]
This is how Markov chains work. I have no sympathy for mloc. He should talk more if it's that important.
